kubernetes-sigs/inference-perf

- OWNERS
> Add Chen Wang to OWNERS

- inference_perf/datagen/__init__.py
- inference_perf/datagen/hf_sharegpt_datagen.py
- pdm.lock
- pyproject.toml
Fixes #25
This PR introduces a data generator utilizing the HF ShareGPT Dataset. It processes ShareGPT data and extracts system prompts from the conversations in the dataset.
> Add HF ShareGPT Data Generator

- inference_perf/client/vllm_client.py
- inference_perf/main.py
- inference_perf/metrics/base.py
- inference_perf/metrics/client.py
- inference_perf/metrics/mock_client.py
- inference_perf/reportgen/base.py
- inference_perf/reportgen/mock_reportgen.py
This PR intorduces an abstract class for metric collection client from services like prometheus and mock metrics client implementation to complete the base framework of the load runner and report generation component.
> Mock metrics client implementation

- .github/workflows/format.yml
- Makefile
- README.md
- config.yml
- inference_perf/client/test_placeholder.py
- inference_perf/config.py
- inference_perf/datagen/hf_sharegpt_datagen.py
- inference_perf/loadgen/__init__.py
- inference_perf/loadgen/load_generator.py
- inference_perf/main.py
- pdm.lock
- pyproject.toml
> Parameterization of CLI tool using config file

- inference_perf/config.py
- inference_perf/datagen/base.py
- inference_perf/datagen/hf_sharegpt_datagen.py
- inference_perf/datagen/mock_datagen.py
- inference_perf/main.py
Fixes an issue with data nad model server api type mismatch by raising error on startup
> Fix: Raising error for api type mismatch

- .gitignore
- config.yml
- examples/vllm/config.yml
- examples/vllm/vllm_server.ipynb
- inference_perf/client/base.py
- inference_perf/client/mock_client.py
- inference_perf/client/vllm_client.py
- inference_perf/config.py
- inference_perf/loadgen/load_generator.py
- inference_perf/main.py
- inference_perf/reportgen/base.py
- pyproject.toml
Thi PR enables multi-stage performance tests. Run logs as follows,
```
Using configuration from: config.yml
Stage 0 - run started
Stage 0 - run completed
Stage 1 - run started
Stage 1 - run completed
Generating Report ..
total_requests: 13
avg_prompt_tokens: 2.0
avg_output_tokens: 28.69
avg_time_per_request: 0.12
```
> Multi-stage performance run

- README.md
- deploy/README.md
- deploy/manifests.yaml
- pyproject.toml
fixes: https://github.com/kubernetes-sigs/inference-perf/issues/51
validated locally
> Add support for cluster-local benchmarking

- inference_perf/datagen/base.py
- inference_perf/datagen/hf_sharegpt_datagen.py
- inference_perf/datagen/mock_datagen.py
- inference_perf/main.py
- inference_perf/utils/custom_tokenizer.py
- pdm.lock
- pyproject.toml
This PR fixes the linting and type-checks
> Lint and type check fixes

- .github/ISSUE_TEMPLATE/blank_issue.md
- .github/ISSUE_TEMPLATE/bug_request.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Fixes https://github.com/kubernetes-sigs/inference-perf/issues/89
> Add issue templates for the repo

- .gitignore
- inference_perf/apis/chat.py
- inference_perf/apis/completion.py
- inference_perf/client/filestorage/__init__.py
- inference_perf/client/filestorage/local.py
- inference_perf/client/modelserver/vllm_client.py
- inference_perf/config.py
- inference_perf/main.py
- inference_perf/reportgen/base.py
- inference_perf/utils/report_file.py
This PR simplifies local report storage onto a path that can be specified on the config as follows
```
storage:
local_storage:
path: ./results
```
> Simplified local report storage

- CONFIG.md
- README.md
ref: https://github.com/kubernetes-sigs/inference-perf/issues/126
Why is this needed:
need a detail description and guidance for how to setup configuration
different environment has different config, such as model name, base URL, api token , etc. I try to set up them then run failed due to lacking experience.
> add config.md file to provide detail description for  config.yml parameters

- examples/vllm/config.yml
- examples/vllm/docker-compose.yml
- examples/vllm/prometheus.yml
- examples/vllm/vllm_server.ipynb
- inference_perf/client/metricsclient/prometheus_client/base.py
- inference_perf/client/modelserver/vllm_client.py
- inference_perf/main.py
This PR fixes the prometheus querying issues with default setup and updates a docker compose based example.
> Prometheus query fixes and examples update

- README.md
replace "Mock" to "mock",  supported data type in config.yml files.
> update datasets type

- inference_perf/apis/completion.py
Noticed an issue where streaming response received from inference gateway was not parsed correctly leading to failures. This change addresses that.
> Fix a parsing issue with streaming requests

- CONFIG.md
- inference_perf/client/filestorage/__init__.py
- inference_perf/client/filestorage/s3.py
- inference_perf/config.py
- inference_perf/main.py
- pdm.lock
- pyproject.toml
Add support for S3 storage.
Adding this:
```yaml
storage:
simple_storage_service:               
bucket_name: "some-bucket"
```
File was uploaded to s3:
> feat: add support for s3 storage

- inference_perf/loadgen/load_generator.py
Short term fix for https://github.com/kubernetes-sigs/inference-perf/issues/141
Adds a randomized first gather to enforce worker event loop yielding. Randomized so workers are offset from eachother.
> Fix QPS accuracy at lower rates

- examples/vllm/config-random.yml
- examples/vllm/config-synthetic.yml
- inference_perf/config.py
- inference_perf/datagen/random_datagen.py
- inference_perf/datagen/synthetic_datagen.py
- inference_perf/main.py
For synthetic and random datasets, use the load stages to calculate the total_count of inputs and outputs.
Fixes #146
> Autocalc total_count

- inference_perf/client/metricsclient/prometheus_client/base.py
Fix for: https://github.com/kubernetes-sigs/inference-perf/issues/166
> Fix Malformed GMP Query URL

- inference_perf/config.py
- inference_perf/datagen/__init__.py
- inference_perf/datagen/cnn_dailymail_datagen.py
- inference_perf/main.py
Following hf_sharegpt_datagen, allows specifying io distribution max output and max input.
Testing against llama3-8b
Config:
```
api:
type: completion
streaming: true
data:
type: cnn_dailymail
load:
type: constant
stages:
- rate: 1
duration: 10
tokenizer:
server:
type: vllm
base_url: "http://localhost:8000"
report:
request_lifecycle:
summary: true
per_stage: true
per_request: true
```
Output:
```
{
"load_summary": {
"count": 10,
"schedule_accuracy": {
"mean": 0.0008664916502311825,
"min": 0.0001644693547859788,
"p10": 0.0002061066683381796,
"p50": 0.0008529323386028409,
"p90": 0.0014685166883282362,
"max": 0.0019052864518016577
},
"send_duration": 9.965216769953258,
"requested_rate": 1.0,
"achieved_rate": 1.0034904639657833
},
"successes": {
"count": 10,
"latency": {
"request_latency": { …
```
> Add cnn_dailymail datagen

- inference_perf/config.py
- inference_perf/datagen/__init__.py
- inference_perf/datagen/hf_billsum_datagen.py
- inference_perf/main.py
Example Config:
```
load:
type: constant
stages:
- rate: 1
duration: 30
api: 
type: completion
server:
type: vllm
model_name: meta-llama/Llama-3.1-8B-Instruct
base_url: http://<server>:80
ignore_eos: true
tokenizer:
pretrained_model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
token: <token>
storage:
google_cloud_storage:
bucket_name: inference-perf-results
data:
type: billsum_conversations
path: datasets/billsum_conversations.json
report:
request_lifecycle:
summary: true
per_stage: true
per_request: false
prometheus:
summary: true
per_stage: false
```
Output Summary:
```
{
"load_summary": {
"count": 30,
"schedule_delay": {
"mean": 0.00114706016999359,
"min": -0.000305728521198034,
"p10": 0.000156184693332761,
"median": 0.00133772497065365,
"p90": 0.00198361872462556,
"max": …
```
> Update inf-perf to use hf-billsum dataset

- inference_perf/loadgen/load_generator.py
Adds log showing the sampled rates used to determine saturation.
> Add debug log for saturation sampling
