.github/workflows/format.yml
Makefile
inference_perf/client/__init__.py
inference_perf/client/base.py
inference_perf/client/mock_client.py
inference_perf/client/vllm_client.py
inference_perf/loadgen/load_generator.py
inference_perf/loadgen/load_timer.py
inference_perf/main.py
inference_perf/reportgen/__init__.py
inference_perf/reportgen/base.py
inference_perf/reportgen/mock_reportgen.py

Fixes #14 
Updated run returns using a test model.
Steps to reproduce:
- Run vLLM as a docker container - [instructions](https://docs.vllm.ai/en/stable/deployment/docker.html)
- Load [GPT2](https://huggingface.co/openai-community/gpt2) model `openai-community/gpt2`
- Run inference-perf as per getting started [directions](https://github.com/kubernetes-sigs/inference-perf?tab=readme-ov-file#getting-started)
```
Run started
Run completed
Generating Report ..
'avg_completion_tokens': 28.714285714285715,
'avg_latency': 0.12395962485710957,
'avg_prompt_tokens': 2.5714285714285716,
'total_requests': 21
```

Adding vLLM Client to inference perf runner

---

Dockerfile
README.md

This change adds a Dockerfile to build and run the benchmark within a container. The change updates the README with the instructions as well.
Fixes https://github.com/kubernetes-sigs/inference-perf/issues/39

Containerize the benchmark

---

config.yml
inference_perf/client/base.py
inference_perf/client/mock_client.py
inference_perf/client/vllm_client.py
inference_perf/config.py
inference_perf/main.py
inference_perf/metrics/README.md
inference_perf/metrics/__init__.py
inference_perf/metrics/base.py
inference_perf/metrics/mock_client.py
inference_perf/metrics/prometheus_client.py
inference_perf/reportgen/__init__.py
inference_perf/reportgen/base.py
inference_perf/reportgen/mock_reportgen.py
pyproject.toml

Issue# https://github.com/kubernetes-sigs/inference-perf/issues/17
Added Prometheus Client that connects to a Prometheus instance to fetch metrics for the benchmark. This is assuming Prometheus has model server metrics.
Engine tested: vLLM
Queue Size
TTFT
TPOT
Input Token Count
Output Token Count
Successful Request Count
Request Latency
If metric_client is not passed in config.yml, the report generation falls back to benchmark request metrics.
TODO
Fetch KV cache usage metric from vLLM server via Prometheus.
As of this PR, metrics for the complete run are reported i.e. metrics for all the stages are aggregated. 
```
Using configuration from: config.yml
Stage 0 - run started
Stage 0 - run completed
Stage 1 - run started
Stage 1 - run completed
Waiting for 20 seconds for Prometheus to …
```

Added Prometheus client to get model server metrics

---

examples/vllm/config-synthetic.yml
examples/vllm/vllm_server.ipynb
inference_perf/client/modelserver/vllm_client.py
inference_perf/datagen/synthetic_datagen.py
inference_perf/main.py
inference_perf/prompts/completion.py

This change makes the output distribution configurable for synthetic data generator similar to input distribution. When specified, the output distribution will follow a normal distribution based on the provided mean and standard deviation. Fixes https://github.com/kubernetes-sigs/inference-perf/issues/65.

Add output distribution to synthetic data generator

---

config.yml
inference_perf/client/modelserver/vllm_client.py
inference_perf/config.py
inference_perf/main.py
inference_perf/prompts/base.py
inference_perf/prompts/chat.py
inference_perf/prompts/completion.py

This change adds the option to ignore end of sequence on responses produced by the model server. This allows us to set max_tokens and get close to the expected tokens.
Fixes https://github.com/kubernetes-sigs/inference-perf/issues/82
With ignore_eos=true and max_tokens=1000
```
"output_len": {
"mean": 914.1739130434783,
"min": 681.0,
"p10": 770.8,
"p50": 979.0,
"p90": 992.8,
"max": 996.0
},
```
With ignore_eos=false and max_tokens=1000
```
"output_len": {
"mean": 337.625,
"min": 4.0,
"p10": 45.300000000000004,
"p50": 328.5,
"p90": 697.9000000000002,
"max": 892.0
},
```

Add the option to ignore end of sequence

---

.github/changelog-config.json
.github/workflows/release.yml

This PR adds automated release management to the project through GitHub Actions and a structured changelog system.
- Added `.github/workflows/release.yml` for automated release processing
- Added `.github/changelog-config.json` for structured changelog generation
- **Automated Release Process**: Triggers on tag pushes matching `v*.*.*`
- **Changelog Generation**: Automatically generates changelogs based on commit history
- **Structured Categories**: Organizes changes into:
- 🚀 Features
- 🐛 Bug Fixes
- 📚 Documentation
- ⚡️ Performance
- 🔧 Dependencies
To create a new release:
1. Create and push a new tag (e.g., `v1.0.0`)
2. The workflow will automatically:
- Generate a changelog from commits
- Create a GitHub release with the changelog
- The workflow is configured to run on semantic …

Add GitHub Release Workflow and Changelog Configuration

---

config.yml
inference_perf/client/metricsclient/base.py
inference_perf/client/metricsclient/mock_client.py
inference_perf/client/metricsclient/prometheus_client.py
inference_perf/config.py
inference_perf/datagen/random_datagen.py
inference_perf/loadgen/load_generator.py
inference_perf/main.py
inference_perf/reportgen/base.py

Solves https://github.com/kubernetes-sigs/inference-perf/pull/95  
This PR implements multi-stage report generation for Prometheus metrics with the following enhancements:
1. Sets stage intervals to match or exceed Prometheus scrape duration, ensuring complete metric collection before the next stage begins
2. Records stage-specific metrics from each stage's start time until the subsequent stage begins
Prometheus metrics lack stage_id label, which can cause boundary inaccuracies between stages. Some metrics may be incorrectly attributed to adjacent stages.
Given `config.yaml`:
```
load:
type: constant
stages:
- rate: 1
duration: 30
- rate: 2
duration: 30
...
report:
request_lifecycle:
summary: true
per_stage: true
per_request: false
prometheus:
summary: true
per_stage: true
```
Saved in …

Multi-stage report generation for Prometheus Metrics

---

.github/workflows/docker-build.yml
.github/workflows/release.yml

This PR implements automated Docker image publishing (to quay.io/inference-perf) for both PR merges and releases. 
In detail, the changes include:
- A new workflow (in .github/workflows/docker‑build.yml) that triggers on PR merges (to main) and builds (and pushes) a Docker image (tagged with the PR number and “latest” for the main branch).
- An update to the release workflow (in .github/workflows/release.yml) so that (on a version tag) a Docker image is also built and pushed (tagged with the release version and “latest”).
- Both workflows use GitHub Actions’ caching (via “cache‑from” and “cache‑to”) for faster builds.
**Required Secrets:**
QUAY_USERNAME (your quay.io username)
QUAY_PASSWORD (your quay.io password or token)
**Testing:**
[x] Verified that the Docker image builds …

Add Docker build and push workflows for PRs and releases

---

inference_perf/datagen/random_datagen.py
inference_perf/reportgen/base.py

Part of https://github.com/kubernetes-sigs/inference-perf/issues/56
Tested with the following load:
```
load:
type: constant
interval: 1.0
stages:
- rate: 1
duration: 10
- rate: 2
duration: 15
```
Snippet from summary report:
```
"successes": {
"count": 57,
"throughput": {
"input_tokens_per_sec": 991.276762334537,
"output_tokens_per_sec": 61.6511605483135,
"total_tokens_per_sec": 1052.92792288285,
"requests_per_sec": 1.95011995075132
},
...
```
Snippet from stage 1 report:
```
"successes": {
"count": 15,
"throughput": {
"input_tokens_per_sec": 348.772345751132,
"output_tokens_per_sec": 42.5222957473787,
"total_tokens_per_sec": 391.29464149851,
"requests_per_sec": 1.34280933939091
},
...
```
Snippet from stage 2 report:
```
"successes": {
"count": 42,
"throughput": { …
```

Added throughput metrics to output report

---

.github/workflows/docker-build.yml

This PR updates the GitHub Actions workflow to trigger Docker build and push jobs on every push to the main branch.
Previously, the workflow was only triggered by pull requests. And if the PR is merged from a forked repo, the secrets are not visible to the action job due to GitHub security settings.
With this change:
- The workflow will now run automatically on every push to main.
- This ensures Docker images are built and published to Quay.io for all direct updates to the main branch, improving release automation and consistency.
- 
No other workflow logic or steps were changed.

Enable Docker Build Workflow on Push to Main Branch

---

.github/workflows/docker-build.yml

**The Problem**
The ${{ secrets.QUAY_USERNAME }} context is only available at the step level, not inside the with: block of another action (like docker/metadata-action). This can cause the tag to be rendered incorrectly (as quay.io//inference-perf:main or with ***).
**The Solution**
Use an environment variable for the username and reference that in your tags.
This PR updates the GitHub Actions workflow to use the environment variable `env.QUAY_USERNAME` (instead of `secrets.QUAY_USERNAME`) when generating Docker image tags.
This change ensures that Docker image tags are correctly formatted, preventing failures during the push step due to invalid tag references.
- No changes to workflow logic or triggers.
- Only the tag generation now references `env.QUAY_USERNAME` for compatibility.

Fix Docker Tag Generation by Using env.QUAY_USERNAME in Workflow

---

.github/workflows/docker-build.yml

This PR updates the GitHub Actions workflow for Docker image builds to use a hardcoded Quay.io organization `inference-perf` and repository name (`quay.io/inference-perf/inference-perf`) when tagging and pushing images.
The `secrets.QUAY_USERNAME` actually differs from the org name.

Update Quay.io Organization Name in Docker Build Workflow

---

config.yml
examples/vllm/config-random.yml
examples/vllm/config.yml
inference_perf/apis/base.py
inference_perf/apis/chat.py
inference_perf/apis/completion.py
inference_perf/client/modelserver/base.py
inference_perf/client/modelserver/mock_client.py
inference_perf/client/modelserver/vllm_client.py
inference_perf/config.py
inference_perf/datagen/base.py
inference_perf/datagen/hf_sharegpt_datagen.py
inference_perf/datagen/mock_datagen.py
inference_perf/datagen/random_datagen.py
inference_perf/datagen/shared_prefix_datagen.py
inference_perf/datagen/synthetic_datagen.py
inference_perf/main.py
inference_perf/reportgen/base.py
tests/apis/test_chat.py
tests/apis/test_completion.py
tests/test_config.py

Addresses https://github.com/kubernetes-sigs/inference-perf/issues/15
Changes:
* Setting `.api.streaming` to true will make all responses streamed (default: False)
* API type config moved from `.api` to `.api.type`
* Report now includes `stream_metrics` section when streaming responses since TPOT, TTFT, and ITL depend on per token latency measurements.
Report snippet from local testing:
```
"successes": {
"count": 33,
"latency": {
"request_latency": {
"mean": 3.31325431142327,
"min": 1.62129471905064,
"p10": 1.67609986825846,
"p50": 2.11507539497688,
"p90": 5.94717199734878,
"max": 6.30658466403838
},
"normalized_time_per_output_token": {
"mean": 0.104340420636009,
"min": 0.0506654599703325,
"p10": 0.0523781208830769,
"p50": 0.0670631669655753,
"p90": 0.189047570470012,
"max": …
```

Add Support for Streaming Requests to Completions API

---

inference_perf/client/modelserver/vllm_client.py
inference_perf/client/requestdatacollector/__init__.py
inference_perf/client/requestdatacollector/multiprocess.py
inference_perf/config.py
inference_perf/loadgen/load_generator.py
inference_perf/main.py
inference_perf/reportgen/base.py

#86 
This adds configuration for multiple worker (processes) that handle request processing up to a configurable limit per worker. A new request data collector was added to receive results via multiprocessing queue.
The load generator pre-schedules request times and pushes onto a request queue that workers pull from until they see an empty request queue and receive a STAGE_END or WORKER_STOP sentinnel.

Add multiprocess, multithreaded loadgen

---

inference_perf/client/filestorage/base.py
inference_perf/client/filestorage/gcs.py
inference_perf/client/metricsclient/prometheus_client.py
inference_perf/client/modelserver/mock_client.py
inference_perf/client/requestdatacollector/multiprocess.py
inference_perf/config.py
inference_perf/datagen/hf_sharegpt_datagen.py
inference_perf/loadgen/load_generator.py
inference_perf/logger.py
inference_perf/main.py
inference_perf/reportgen/base.py
tests/test_config.py
tests/test_logger.py

Resolves https://github.com/kubernetes-sigs/inference-perf/issues/48
Use logging methods with levels instead of print. Confirmed the make lint and make test passed locally.
<details><summary>Details</summary>
```console
$ git show HEAD | head -n 5
commit 5c98255215ce47e08a83a9079dd8671f2f0931e6
Author: Shotaro Kohama <khmshtr28@gmail.com>
Date:   Tue Jun 3 21:29:56 2025 -0700
Replace print with logging with levels
$ make lint
Linting Python files with ruff check...
.venv/bin/ruff check
All checks passed!
$ make test | tail
configfile: pyproject.toml
testpaths: .
collected 10 items
tests/apis/test_chat.py .                                                [ 10%]
tests/apis/test_completion.py .                                          [ 20%]
tests/test_config.py .. …
```

Use logging methods with levels instead of print

---

inference_perf/client/requestdatacollector/multiprocess.py
inference_perf/loadgen/load_generator.py

Slower machines may cause starvation on request_queue join, causing loadgen to hang. This change reorders the STAGE_END signal and joins.
This ensures that workers gather tasks only after the full request queue is emptied for the stage.
The loadgen now joins the workers' status queues before joining the request_queue.

Fix loadgen hang

---

inference_perf/client/modelserver/vllm_client.py
inference_perf/config.py
inference_perf/main.py

This pull request introduces API key authentication for the `vLLMClient`. This allows `inference-perf` to connect to vLLM server instances that are protected and [require an `Authorization` header](https://docs.vllm.ai/en/stable/getting_started/quickstart.html?h=vllm_api_key#openai-compatible-server) for requests.
* **`inference_perf/client/modelserver/vllm_client.py`**:
* The `__init__` method of `VLLMClient` has been updated to accept an optional `api_key` argument.
* In the `process_request` method, an `Authorization` header with a Bearer token is now added to the request if an `api_key` was provided during client initialization.
* **`inference_perf/main.py`**:
* The `VLLMClient` is now instantiated with the `api_key` from the server configuration (`config.server.api_key`), enabling …

Add support for api_key #116

---

.github/workflows/release.yml

This PR fixes the Docker build workflow issue where the image tag was showing as 'quay.io/***/inference-perf' instead of the proper username.
- Remove `docker/metadata-action@v5` to avoid secret substitution issues
- Set image name and tags as environment variables first, then use them directly
- Add comprehensive debugging output for environment variables
- Directly specify Docker tags and labels in build action
- Add validation and debug steps for better troubleshooting
- The workflow now shows all environment variables for debugging
- Docker tags are constructed directly from environment variables
- This should resolve the 'invalid reference format' error
Fixes the Docker build error: 'invalid tag \"quay.io/***/inference-perf:v0.1.0\": invalid reference format'"
Fix #119

fix: improve Docker build workflow with better secret handling and debugging

---

.github/workflows/release.yml

fix: improve release workflow with proper changelog and Docker image handling

---

examples/vllm/config-shared-prefix.yml
examples/vllm/config-synthetic.yml

update "examples/vllm/config-shared-prefix.yml " and "examples/vllm/config-synthetic.yml"
from 
api: completion 
to 
api:
type: completion 
otherwise when run config yml follow these examples , it will response 
pydantic_core._pydantic_core.ValidationError: 1 validation error for Config
api
Input should be a valid dictionary or instance of APIConfig [type=model_type, input_value='completion', input_type=str]
For further information visit https://errors.pydantic.dev/2.11/v/model_type

update example config yml files

---

inference_perf/client/modelserver/vllm_client.py

The original code sets tokenizer model name to model_name in every situation which makes `pretrained_model_name_or_path` in `config.yml` useless. Therefore, I add some conditions to avoid that.
https://github.com/kubernetes-sigs/inference-perf/issues/159

fix: only assign tokenizer to model_name when not configured

---

CONFIG.md

ref: https://github.com/kubernetes-sigs/inference-perf/issues/150
why it is needed:
streaming: true needs to be set for some metrics to be reported. Default is non-streaming requests which would not give us these metrics. Might be good to update in the documentation too to make it clear.

update streaming part in the documentation too to make it clear

---

CONFIG.md
inference_perf/client/filestorage/s3.py
inference_perf/config.py
inference_perf/datagen/hf_sharegpt_datagen.py
inference_perf/main.py

This PR adds support for running inference-perf offline. 
Fixes https://github.com/kubernetes-sigs/inference-perf/issues/138 & https://github.com/kubernetes-sigs/inference-perf/issues/127
Added the following config params for data.type=shareGPT:
```
data:
type: shareGPT
path: ./data/shareGPT # path to the downloaded shareGPT dataset
```
1. Update server.model_name, tokenizer.pretrained_model_name_or_path with the location of your downloaded model.
2. Set data.path with the location of your downloaded dataset. If data.path is empty, download the dataset from huggingface.
This PR also fixes linting errors in `inference_perf/client/filestorage/s3.py`, `inference_perf/main.py`. There are a few other validation error that cause pre-commit hook to fail. Will raise a separate PR to fix them.

Support for running inference-perf offline

---

inference_perf/config.py
inference_perf/datagen/base.py
inference_perf/datagen/random_datagen.py
inference_perf/datagen/shared_prefix_datagen.py
inference_perf/datagen/synthetic_datagen.py
inference_perf/loadgen/load_generator.py
inference_perf/loadgen/load_timer.py
pdm.lock
pyproject.toml

Loadgen architecture performance improvements (and qps accuracy improvements).
Achieves > 10k qps in some cases (large machine, random/synthetic/shared_prefix datasets, low request latency).
Improved schedule accuracy in low qps scenarios.
Fixes #188 
- Updates default num_wokers == num_cpus
- Updates default worker_max_concurrency to 100
- Sharegpt remains using the old path, a later PR can support preprocessing the dataset (~100s latency vs 6s for current streaming method). Preprocessing is only really useful for > 1000qps.
- Use uvloop in worker processes for drop in event loop improvement.
- Adds sleep(0) in worker loop to yield event loop
- Automated load testing #40 
- Configurable HF datagen preprocessing to support deferring get_request to workers #191 
- Enforce worker scheduling …

Defer InferenceAPIData gen to worker procs

---

README.md
inference_perf/reportgen/base.py

New name more clearly indicates that 0 is better.
Added README example.

Rename schedule_accuracy to schedule_delay

---

CONFIG.md
inference_perf/client/modelserver/vllm_client.py
inference_perf/config.py

Support custom http headers in inference requests

---

inference_perf/client/metricsclient/base.py
inference_perf/client/modelserver/base.py
inference_perf/client/modelserver/vllm_client.py
inference_perf/reportgen/base.py

example output:
{"load_summary": {}, "successes": {"count": 0, "rate": 0.0, "prompt_len": {"mean": 0, "rate": 0.0}, "output_len": {"mean": 0, "rate": 0.0}, "queue_len": {"mean": 0}, "request_latency": {"mean": 0.0, "p50": 0.0, "p90": 0.0, "p99": 0.0}, "time_to_first_token": {"mean": 0.0, "p50": 0.0, "p90": 0.0, "p99": 0.0}, "time_per_output_token": {"mean": 0.0, "p50": 0.0, "p90": 0.0, "p99": 0.0}, "kv_cache_usage_percentage": {"mean": 0.0, "p50": 0.0, "p90": 0.0, "p99": 0.0}, "num_requests_swapped": {"mean": 0}, "num_preemptions_total": {"mean": 0}}, "failures": {}}
Metrics are zero since I ran this without the prometheus server, but metrics are outputted correctly.

Add vllm metrics [preemptions and swapped requests] to prometheus metrics

---

examples/sglang/.gitignore
examples/sglang/config-random.yml
examples/sglang/config-shared-prefix.yml
examples/sglang/config-synthetic.yml
examples/sglang/config.yml
examples/sglang/docker-compose.yml
examples/sglang/main.ipynb
examples/sglang/prometheus.yml
examples/vllm/.gitignore
examples/vllm/main.ipynb
inference_perf/apis/chat.py
inference_perf/client/filestorage/__init__.py
inference_perf/client/metricsclient/base.py
inference_perf/client/metricsclient/prometheus_client/base.py
inference_perf/client/modelserver/__init__.py
inference_perf/client/modelserver/base.py
inference_perf/client/modelserver/openai_client.py
inference_perf/client/modelserver/sglang_client.py
inference_perf/client/modelserver/vllm_client.py
inference_perf/config.py
inference_perf/datagen/hf_sharegpt_datagen.py
inference_perf/datagen/random_datagen.py
inference_perf/datagen/shared_prefix_datagen.py
inference_perf/datagen/synthetic_datagen.py
inference_perf/main.py
inference_perf/reportgen/base.py

This PR adds support for [SGlang server](https://docs.sglang.ai/index.html). Fixes #194

Added SGlang server support

---

inference_perf/client/metricsclient/base.py
inference_perf/client/modelserver/base.py
inference_perf/client/modelserver/openai_client.py
inference_perf/client/modelserver/sglang_client.py
inference_perf/client/modelserver/vllm_client.py
inference_perf/datagen/cnn_dailymail_datagen.py
inference_perf/datagen/hf_sharegpt_datagen.py
inference_perf/reportgen/base.py

Adds prefix cache hits and queries, reports as hit percentage. Also adds pdm fixes.
Testing:
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
2025-09-09 16:41:21,906 - inference_perf.config - INFO - Using configuration from: metrics.yml
2025-09-09 16:41:21,909 - inference_perf.config - INFO - Benchmarking with the following config:
api:
type: completion
streaming: true
headers: null
data:
type: shareGPT
path: null
input_distribution: null
output_distribution: null
shared_prefix: null
load:
type: constant
interval: 1.0
stages:
- rate: 1
duration: 30
num_workers: 88
worker_max_concurrency: 100
worker_max_tcp_connections: 2500
metrics:
type: prometheus
prometheus:
google_managed: …
```

Add vllm prefix metrics

---

inference_perf/client/filestorage/local.py
inference_perf/main.py
inference_perf/reportgen/base.py
inference_perf/utils/report_file.py

This adds the config yaml to the report directory by default. The written config can be used directly to repeat the benchmark.
Fixes https://github.com/kubernetes-sigs/inference-perf/issues/165

Write config.yaml to report directory

---

.github/workflows/release.yml
deploy/inference-perf/templates/job.yaml
deploy/inference-perf/values.yaml

With this, we can install inference-perf via `helm install RELEASE_NAME oci://quay.io/inference-perf/charts/inference-perf -f values.yml`.
Custom `values.yml` is needed because [no image is specified currently](https://github.com/kubernetes-sigs/inference-perf/blob/main/deploy/inference-perf/values.yaml#L3).
I also [tested this](https://github.com/ExplorerRay/inference-perf/actions/runs/18069792355/job/51418055633) on my local fork with `ghcr.io` to make sure that this action works well.
https://github.com/kubernetes-sigs/inference-perf/issues/218

ci: push helm chart to OCI registry when release

---

inference_perf/analysis/analyze.py

The current analyze plot is generated based on the expected rate. This may undercover some setup mistake while doing the analysis. Changed to `achieved_rate`

use achieved_rate in the report graph.
